import { Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { categoryContent, stories } from "@/lib/editorial-data";
import { ReviewGrid } from "@/components/site/ReviewArticle";
import { reviews, reviewsByCategory, type Category } from "@/lib/reviews-data";

export function SectionLabel({ children, dark = false }: { children: React.ReactNode; dark?: boolean }) { return <div className={`mb-6 flex items-center gap-3 text-xs font-extrabold uppercase ${dark ? "text-paper/70" : "text-muted-foreground"}`}><span className="h-2 w-2 bg-primary" />{children}</div>; }

export function NewsletterBand() { return <section className="bg-accent text-accent-foreground"><div className="mx-auto grid max-w-[1440px] gap-8 px-5 py-14 lg:grid-cols-[1.25fr_1fr] lg:items-end lg:px-10 lg:py-20"><div><SectionLabel dark>Tuesday intelligence</SectionLabel><h2 className="max-w-3xl font-display text-4xl font-extrabold leading-[1.05] md:text-6xl">One sharp briefing. Zero launch-day noise.</h2></div><div><p className="mb-6 max-w-lg leading-7 text-paper/75">The week’s important software shifts, tested tools, and practical buying advice.</p><Button asChild className="h-12 rounded-none bg-paper px-6 text-ink hover:bg-paper/90"><Link to="/newsletter">Join the briefing <ArrowRight /></Link></Button></div></div></section>; }

export function HomePage() {
  const lead = stories[0];
  if (!lead) return null;
  return <>
    <section className="border-b border-border"><div className="mx-auto max-w-[1440px] px-5 py-7 lg:px-10"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase text-muted-foreground">Independent software intelligence</p><p className="hidden text-xs font-bold uppercase text-muted-foreground sm:block">Edition 01 · 2026</p></div></div></section>
    <section className="mx-auto grid max-w-[1440px] lg:grid-cols-[1.15fr_.85fr]">
      <div className="flex flex-col justify-center border-b border-border px-5 py-12 lg:border-b-0 lg:border-r lg:px-10 lg:py-20"><SectionLabel>{lead.eyebrow}</SectionLabel><h1 className="max-w-4xl font-display text-5xl font-extrabold leading-[.98] md:text-7xl xl:text-[5.6rem]">Cut through the hype. Choose what works.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">TheHyped tests AI tools, business software, and finance apps with one question: does this make the work better?</p><div className="mt-9 flex flex-wrap items-center gap-5"><Button asChild size="lg" className="h-12 rounded-none"><Link to="/reviews/$slug" params={{ slug: "atlas-ai" }}>Read the lead review <ArrowRight /></Link></Button><span className="text-xs font-bold uppercase text-muted-foreground">12 min read · Sample review</span></div></div>
      <Link to="/reviews/$slug" params={{ slug: "atlas-ai" }} className="group relative min-h-[430px] overflow-hidden bg-ink lg:min-h-[690px]"><img src={lead.image} alt="Laptop displaying abstract analytics interface" width={1200} height={900} className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.02]"/><div className="absolute inset-x-0 bottom-0 bg-ink/90 p-6 text-paper md:p-9"><p className="text-xs font-bold uppercase text-primary">Reviewed this week</p><div className="mt-3 flex items-end justify-between gap-5"><h2 className="max-w-xl font-display text-2xl font-bold md:text-4xl">{lead.title}</h2><span className="font-display text-4xl font-extrabold text-paper">{lead.score}</span></div></div></Link>
    </section>
    <section className="bg-paper py-16 lg:py-24"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><div className="mb-10 flex items-end justify-between"><div><SectionLabel>THE SHORTLIST</SectionLabel><h2 className="font-display text-4xl font-extrabold md:text-6xl">Six tools worth your time.</h2></div><Link to="/reviews" className="hidden items-center gap-2 text-sm font-bold uppercase md:flex">All reviews <ArrowRight className="size-4"/></Link></div><ReviewGrid items={reviews} /></div></section>
    <section className="bg-ink py-16 text-paper lg:py-24"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><SectionLabel dark>THE DESKS</SectionLabel><div className="grid gap-px bg-paper/20 md:grid-cols-3">{Object.entries(categoryContent).map(([path,cat],i) => <Link key={path} to={path as "/ai-tools"|"/business-software"|"/finance-apps"} className="group min-h-72 bg-ink p-7 transition-colors hover:bg-paper hover:text-ink"><p className="text-xs font-bold uppercase text-primary">0{i+1} / {cat.label}</p><h3 className="mt-14 font-display text-3xl font-extrabold leading-tight">{cat.title}</h3><p className="mt-5 text-sm leading-6 opacity-65">{cat.intro}</p><ArrowRight className="mt-7 transition-transform group-hover:translate-x-2"/></Link>)}</div></div></section>
    <section className="py-16 lg:py-24"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><SectionLabel>DEEP READS</SectionLabel><div className="grid gap-8 md:grid-cols-2">{stories.slice(1).map((story) => <Link to={story.path} key={story.title} className="group"><div className="aspect-[4/3] overflow-hidden bg-secondary"><img src={story.image} alt="Abstract technology workspace" loading="lazy" width={1200} height={900} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.02]"/></div><p className="mt-5 text-xs font-bold uppercase text-primary">{story.eyebrow}</p><h3 className="mt-2 font-display text-2xl font-extrabold md:text-4xl">{story.title}</h3><p className="mt-3 max-w-xl leading-7 text-muted-foreground">{story.dek}</p></Link>)}</div></div></section>
    <NewsletterBand />
  </>;
}

export function CollectionPage({ kind }: { kind: "reviews"|"compare"|"blog" }) {
 const data: [string, string, string] = kind === "reviews" ? ["Reviews", "Real tests. Clear verdicts.", "We examine setup, daily use, limits, pricing, and who each product is actually for."] : kind === "compare" ? ["Compare", "Make the shortlist shorter.", "Side-by-side breakdowns that surface the trade-offs product pages prefer to hide."] : ["Field Notes", "Ideas for better digital work.", "Analysis, operating lessons, and useful context beyond the product score."];
 if (kind === "reviews") return <><PageIntro label={data[0]} title={data[1]} intro={data[2]}/><section className="py-14 lg:py-20"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><ReviewGrid items={reviews}/></div></section><NewsletterBand/></>;
 return <><PageIntro label={data[0]} title={data[1]} intro={data[2]}/><section className="py-14 lg:py-20"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 md:grid-cols-2 lg:px-10">{stories.map((s,i)=><Link key={s.title} to={kind === "compare" && i === 0 ? "/compare/atlas-ai-vs-flowdesk" : s.path} className={i===0 ? "md:col-span-2" : ""}><div className={`${i===0 ? "aspect-[16/7]" : "aspect-[4/3]"} overflow-hidden`}><img src={s.image} alt="Editorial technology scene" width={1200} height={900} className="h-full w-full object-cover"/></div><p className="mt-5 text-xs font-bold uppercase text-primary">{s.eyebrow}</p><h2 className="mt-2 max-w-4xl font-display text-3xl font-extrabold md:text-5xl">{s.title}</h2><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">{s.dek}</p></Link>)}</div></section><NewsletterBand/></>;
}

export function PageIntro({ label, title, intro }: {label:string;title:string;intro:string}) { return <section className="border-b border-border"><div className="mx-auto max-w-[1440px] px-5 py-16 lg:px-10 lg:py-24"><SectionLabel>{label}</SectionLabel><h1 className="max-w-5xl font-display text-5xl font-extrabold leading-[1.02] md:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">{intro}</p></div></section>; }

export function CategoryPage({ slug }: {slug:keyof typeof categoryContent}) { const c=categoryContent[slug]; const items=reviewsByCategory(slug.replace("/","") as Category); return <><PageIntro label={c.label} title={c.title} intro={c.intro}/><section className="py-14 lg:py-20"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><ReviewGrid items={items}/></div></section><NewsletterBand/></> }


function ArticleSection({title,children}:{title:string;children:React.ReactNode}) {return <section><h2>{title}</h2>{children}</section>}

export function ComparisonPage() { const image=stories[1]?.image; return <article><div className="bg-ink text-paper"><div className="mx-auto max-w-[1200px] px-5 py-16 lg:px-10 lg:py-24"><p className="text-xs font-bold uppercase text-primary">Head-to-head · Sample comparison</p><h1 className="mt-5 max-w-5xl font-display text-5xl font-extrabold leading-[1.02] md:text-7xl">Atlas AI vs Flowdesk: which is better for modern research?</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-paper/65">Atlas wins on depth and traceability. Flowdesk wins when speed and simple team handoffs matter most.</p></div></div>{image&&<div className="mx-auto max-w-[1200px] px-5 pt-12 lg:px-10"><img src={image} alt="Two devices representing competing software products" width={1200} height={900} className="aspect-[16/8] w-full object-cover"/></div>}<div className="mx-auto max-w-[900px] px-5 py-16"><SectionLabel>THE SHORT ANSWER</SectionLabel><div className="grid gap-5 sm:grid-cols-2"><Choice name="Atlas AI" score="9.1" text="Pick it for complex, source-heavy research and structured projects." winner/><Choice name="Flowdesk" score="8.8" text="Pick it for fast collaboration, summaries, and lighter workflows."/></div><div className="prose-editorial mt-14"><ArticleSection title="Feature by feature"><p>Atlas is built around durable research spaces; Flowdesk is optimized around motion. The difference becomes clear after a week: Atlas preserves the reasoning trail, while Flowdesk helps a team push work forward with less ceremony.</p></ArticleSection><ArticleSection title="Pricing comparison"><p>Both products offer a useful entry tier. Atlas becomes more valuable as the number of sources grows; Flowdesk’s team plan makes more sense when collaboration volume is the main constraint.</p></ArticleSection><ArticleSection title="Who should choose each"><ul><li><strong>Choose Atlas:</strong> analysts, strategists, researchers, and evidence-heavy content teams.</li><li><strong>Choose Flowdesk:</strong> agencies, operators, and smaller teams prioritizing speed.</li></ul></ArticleSection><ArticleSection title="Final verdict"><p>Atlas AI is our overall pick because its strengths become more valuable as a project becomes more important. Flowdesk remains the sharper choice for fast-moving operational teams.</p></ArticleSection></div><p className="mt-12 border-l-4 border-primary pl-5 text-sm text-muted-foreground">Demonstration comparison: product names, features, and pricing are illustrative.</p></div></article> }
function Choice({name,score,text,winner=false}:{name:string;score:string;text:string;winner?:boolean}) {return <div className={`border p-6 ${winner?"border-primary bg-primary text-primary-foreground":"border-border"}`}><p className="text-xs font-bold uppercase">{winner?"Our pick":"Strong alternative"}</p><div className="mt-5 flex justify-between"><h2 className="font-display text-3xl font-extrabold">{name}</h2><span className="font-display text-2xl font-extrabold">{score}</span></div><p className="mt-5 text-sm leading-6 opacity-75">{text}</p></div>}

export function SimplePage({label,title,children}:{label:string;title:string;children:React.ReactNode}) {return <div className="mx-auto max-w-[1000px] px-5 py-16 lg:px-10 lg:py-24"><SectionLabel>{label}</SectionLabel><h1 className="font-display text-5xl font-extrabold md:text-7xl">{title}</h1><div className="prose-editorial mt-12">{children}</div></div>}
